import { NextResponse } from 'next/server';

const TEMPLATES = [
  {
    id: 'blog-post',
    name: '📝 Blog Post',
    category: 'Content',
    title: 'Write blog post: [Topic]',
    description: 'Write a comprehensive, SEO-optimized blog post for fretcoach.ai/blog.\n\nRequirements:\n- 1500-2000 words\n- Include introduction, 3-5 sections with headers, and conclusion\n- Natural keyword integration\n- Engaging, conversational tone for guitar learners\n- Include practical tips or exercises where relevant',
    tags: ['content', 'blog', 'seo'],
    priority: 'medium',
    suggestedAgent: 'ContentMill',
  },
  {
    id: 'social-batch',
    name: '🐦 Social Media Batch',
    category: 'Content',
    title: 'Create social media posts: [Platform/Topic]',
    description: 'Create a batch of engaging social media posts for FretCoach.ai.\n\nRequirements:\n- 10-15 posts per batch\n- Mix of educational tips, motivation, humor, and engagement\n- Include relevant hashtags\n- Vary formats: questions, tips, quotes, mini-lessons',
    tags: ['content', 'social', 'marketing'],
    priority: 'medium',
    suggestedAgent: 'ContentMill',
  },
  {
    id: 'lesson-outline',
    name: '📐 Lesson/Course Outline',
    category: 'Education',
    title: 'Design course: [Course Name]',
    description: 'Design a structured course outline for FretCoach.ai.\n\nRequirements:\n- Clear learning objectives for each module\n- Progressive difficulty\n- Include practice exercises and assessments\n- Estimated time per lesson\n- Prerequisites noted',
    tags: ['education', 'course-design'],
    priority: 'high',
    suggestedAgent: 'LessonArchitect',
  },
  {
    id: 'lick-generation',
    name: '🎸 Lick/Tab Generation',
    category: 'Education',
    title: 'Generate licks: [Style/Scale]',
    description: 'Generate guitar licks with tab notation.\n\nRequirements:\n- Include standard tab notation\n- Note the scale/key used\n- Include tempo suggestion\n- Difficulty rating (beginner/intermediate/advanced)\n- Playing tips for each lick',
    tags: ['tabs', 'licks', 'education'],
    priority: 'medium',
    suggestedAgent: 'TabSmith',
  },
  {
    id: 'email-sequence',
    name: '📧 Email Sequence',
    category: 'Marketing',
    title: 'Write email sequence: [Purpose]',
    description: 'Write an email nurture/drip sequence for FretCoach.ai subscribers.\n\nRequirements:\n- Subject lines with A/B variants\n- Compelling preview text\n- Clear CTA in each email\n- Personalization tokens\n- Proper spacing and timing between emails',
    tags: ['email', 'marketing', 'nurture'],
    priority: 'high',
    suggestedAgent: 'ContentMill',
  },
  {
    id: 'seo-research',
    name: '🦅 SEO Research',
    category: 'Marketing',
    title: 'SEO research: [Topic/Area]',
    description: 'Conduct SEO keyword research and optimization recommendations.\n\nRequirements:\n- Primary and secondary keywords\n- Search volume estimates\n- Competition analysis\n- Content gap opportunities\n- On-page optimization suggestions',
    tags: ['seo', 'research', 'marketing'],
    priority: 'medium',
    suggestedAgent: 'SEOHawk',
  },
  {
    id: 'theory-explainer',
    name: '🧠 Music Theory Explainer',
    category: 'Education',
    title: 'Explain: [Theory Concept]',
    description: 'Create a clear, guitarist-friendly explanation of a music theory concept.\n\nRequirements:\n- Start with why it matters for guitarists\n- Use fretboard diagrams/examples where possible\n- Progressive explanation (simple → detailed)\n- Include practical application examples\n- Practice exercises to internalize the concept',
    tags: ['theory', 'education'],
    priority: 'medium',
    suggestedAgent: 'TheoryBot',
  },
  {
    id: 'competitive-analysis',
    name: '📊 Competitive Analysis',
    category: 'Business',
    title: 'Competitive analysis: [Competitor/Area]',
    description: 'Analyze competitors in the guitar learning space.\n\nRequirements:\n- Feature comparison matrix\n- Pricing analysis\n- Strengths and weaknesses\n- Market positioning\n- Opportunities for differentiation',
    tags: ['business', 'strategy', 'research'],
    priority: 'high',
    suggestedAgent: 'BizOps',
  },
  {
    id: 'community-strategy',
    name: '💬 Community Strategy',
    category: 'Growth',
    title: 'Community strategy: [Platform/Initiative]',
    description: 'Design a community engagement strategy for FretCoach.ai.\n\nRequirements:\n- Platform selection rationale\n- Content calendar\n- Engagement tactics\n- Growth metrics/KPIs\n- Moderation guidelines',
    tags: ['community', 'growth', 'engagement'],
    priority: 'medium',
    suggestedAgent: 'CommunityPulse',
  },
  {
    id: 'backing-track',
    name: '🎵 Backing Track Spec',
    category: 'Product',
    title: 'Backing track spec: [Genre/Key]',
    description: 'Write a detailed specification for a backing track.\n\nRequirements:\n- Genre, key, tempo, time signature\n- Chord progression with measures\n- Suggested scales for soloing\n- Arrangement notes (intro, verse, chorus, bridge)\n- Difficulty level and target audience',
    tags: ['backing-track', 'product', 'music'],
    priority: 'low',
    suggestedAgent: 'TrackMaster',
  },
];

export async function GET() {
  return NextResponse.json(TEMPLATES);
}
